apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: ui-tg-config
  namespace: ui
spec:
  targetReference:
    kind: Service
    name: ui
  defaultConfiguration:
    targetType: ip
  routeConfigurations:
    - routeIdentifier:
        kind: HTTPRoute
        namespace: ui
        name: ui-route
      targetGroupProps:
        healthCheckConfig:
          healthCheckProtocol: http
          healthCheckPath: /actuator/health/liveness
          matcher:
            httpCode: "200"
