nodeSelector:
  kubernetes.io/os: linux
  workload: observability

tolerations:
  - key: workload
    operator: Equal
    value: observability
    effect: NoSchedule

admissionWebhooks:
  certManager:
    enabled: false
  autoGenerateCert:
    enabled: true
    recreate: true

manager:
  extraArgs:
    - --enable-go-instrumentation=true
