prometheus:
  enabled: true
  prometheusSpec:
    enableRemoteWriteReceiver: true

alertmanager:
  enabled: true

grafana:
  enabled: true
  service:
    type: ClusterIP
  ingress:
    enabled: false
