prometheus:
  enabled: true
  prometheusSpec:
    nodeSelector:
      workload: observability
    tolerations:
      - key: workload
        operator: Equal
        value: observability
        effect: NoSchedule
    enableRemoteWriteReceiver: true
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ""
          accessModes: ["ReadWriteOnce"]
          selector:
            matchLabels:
              app.kubernetes.io/name: retained-prometheus-tsdb
          resources:
            requests:
              storage: 20Gi

alertmanager:
  enabled: true
  alertmanagerSpec:
    alertmanagerConfigMatcherStrategy:
      type: None
    alertmanagerConfigSelector:
      matchLabels:
        release: prometheus
    nodeSelector:
      workload: observability
    tolerations:
      - key: workload
        operator: Equal
        value: observability
        effect: NoSchedule
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: ""
          accessModes: ["ReadWriteOnce"]
          selector:
            matchLabels:
              app.kubernetes.io/name: retained-alertmanager-data
          resources:
            requests:
              storage: 10Gi

grafana:
  enabled: true
  nodeSelector:
    workload: observability
  tolerations:
    - key: workload
      operator: Equal
      value: observability
      effect: NoSchedule
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::255945442255:role/retail-store-grp5-grafana-irsa
  podAnnotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::255945442255:role/retail-store-grp5-grafana-irsa
    eks.amazonaws.com/audience: sts.amazonaws.com
    eks.amazonaws.com/sts-regional-endpoints: "true"
  env:
    AWS_REGION: ap-southeast-1
  plugins:
    - grafana-x-ray-datasource
  additionalDataSources:
    - name: AWS X-Ray
      type: grafana-x-ray-datasource
      access: proxy
      isDefault: false
      jsonData:
        authType: default
        defaultRegion: ap-southeast-1
  service:
    type: ClusterIP
  ingress:
    enabled: false
  persistence:
    enabled: true
    type: pvc
    existingClaim: prometheus-grafana-retained
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "default"
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          updateIntervalSeconds: 10
          allowUiUpdates: true
          options:
            path: /tmp/dashboards
